name: Build and release to Chrome Web Store

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXTENSION_ID: ${{ vars.EXTENSION_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          run_install: false
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -g chrome-webstore-upload-cli
      - name: Build and zip extension
        run: pnpm build && zip -r chrome-extension.zip dist
      - name: Upload to Chrome Web Store
        run: |
          chrome-webstore-upload upload \
            --source chrome-extension.zip \
            --extension-id ${{ env.EXTENSION_ID }} \
            --client-id ${{ secrets.GOOGLE_CLIENT_ID }} \
            --client-secret ${{ secrets.GOOGLE_CLIENT_SECRET }} \
            --refresh-token ${{ secrets.GOOGLE_REFRESH_TOKEN }}
