name: Build and release Beta Version

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
      VITE_COMMIT_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          run_install: false
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: .nvmrc
          registry-url: https://registry.npmjs.org
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Build and package extension
        run: pnpm build:beta && zip -r chrome-extension-beta.zip dist
      - name: Upload extension to Slack
        uses: ./.github/actions/release-beta
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.SLACK_CHANNEL_ID }}
          # The commit message is only present on push events
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          COMMIT_SHA: ${{ github.sha }}